Lodestone-Team/lodestone

package-lock.json
package.json
public/mockServiceWorker.js
src/components/DashboardLayout/TopNav.tsx

From issue: #37 
- Added avatar icon
- Added settings icon

Top navigation bar changes

---

src/components/Atoms/Button.tsx
src/components/Atoms/Config/SelectBox.tsx
src/components/Atoms/Config/ToggleBox.tsx
src/components/Atoms/Form/ComboField.tsx
src/components/Atoms/Form/RadioField.tsx
src/components/Atoms/Form/SelectCoreField.tsx
src/components/Atoms/Form/SelectField.tsx
src/components/Atoms/Label.tsx
src/components/Atoms/LoadingStatusIcon.tsx
src/components/Atoms/NotificationCard.tsx
src/components/DashboardLayout/NotificationPanel.tsx
src/components/DashboardLayout/TopNav.tsx
src/components/FileViewer.tsx
src/components/GameConsole.tsx
src/components/InstanceCard.tsx
src/components/InstanceLoadingCard.tsx
src/components/Minecraft/MinecraftSettingCard.tsx
src/globals.css
src/pages/dashboard.tsx
src/pages/settings.tsx
src/utils/util.ts
tailwind.config.js

Closes #45
- Added new colors
- Renamed Ochre to Yellow
- Added new button variants
- Added our `focus-visible` style to toggles
- Refactored `Label` component to use `clsx`
- Added default text color `text-gray-300` globally

Cleaned up design

---

src/components/DashboardLayout/TopNav.tsx

Added status indicator to top nav

Resolved Issue 43

---

src/components/Atoms/Button.tsx
src/components/FileViewer.tsx

- Always display label (but "hide" it when loading).
- Add the loading icon on top
Re: #52

Maintain button size while loading

---

pages/index.tsx
src/components/Atoms/Avatar.tsx
src/components/DashboardLayout/DashboardLayout.tsx
src/components/DashboardLayout/TopNav.tsx
src/components/LoginLayout.tsx
src/pages/login/CoreConfigNew.tsx
src/pages/login/CoreConnect.tsx
src/pages/login/CoreSelectExisting.tsx
src/pages/login/CoreSetupNew.tsx
src/pages/login/UserLogin.tsx
src/pages/login/UserSelectExisting.tsx
src/utils/util.ts
tailwind.config.js

Added detection of "not setup" cores on `DashboardLayout`, and core selection screens.
We are still missing auto login after setup and key-less setup using Tauri
Closes #46

Rough "core" first time setup flow

---

pages/index.tsx
src-tauri/Cargo.lock
src-tauri/src/main.rs
src/components/Atoms/Form/InputField.tsx
src/pages/login/CoreSetupNew.tsx
src/pages/login/UserSelectExisting.tsx
src/utils/hooks.ts
src/utils/tauriUtil.ts

- Auto-fills setup key if using Tauri
- Auto sets the current token to the owner's token, if the token is empty (user is logged out)
The owner's token part should probably be more obvious. Might need a redesign to accommodate that since currently we only have space for 2 buttons

Tauri password and key bypass

---

.eslintrc.json
.github/workflows/desktop.yml
pages/index.tsx
src/components/DashboardLayout/DashboardLayout.tsx
src/components/DashboardLayout/TopNav.tsx
src/data/BrowserLocationContext.tsx
src/data/EventStream.ts
src/pages/home.tsx
src/pages/login/CoreConnect.tsx
src/pages/login/CoreSelectExisting.tsx
src/pages/login/CoreSetupNew.tsx
src/pages/login/FirstTime.tsx
src/pages/login/UserLogin.tsx
src/pages/login/UserSelectExisting.tsx
src/pages/notfound.tsx
src/utils/hooks.ts
src/utils/router/MyNavigate.tsx
src/utils/router/RequireCore.tsx
src/utils/router/RequireToken.tsx
src/utils/tauriUtil.ts
src/utils/util.ts
tailwind.config.js

- Added 404 pages
- Added redirects for when no core was stored
- Added redirects for when the user is not logged in
- Added first time setup page
- Added "download" buttons to select core page and connect core page
- Made custom `MyNavigate` components for react router

Improved first time setup experience

---

package-lock.json
package.json
pages/_app.tsx
pages/index.tsx
src/components/ClipboardTextfield.tsx
src/components/FileViewer.tsx
src/components/InstanceCard.tsx
src/components/Minecraft/MinecraftSettingCard.tsx
src/data/EventStream.ts
src/globals.css
src/pages/dashboard.tsx
src/utils/util.ts

(#56) Added toasts

---

src/utils/router/RequireSetup.tsx
src/utils/router/RequireToken.tsx

hot fix: fixed some redirects

---

src/pages/login/CoreConnect.tsx
src/pages/login/FirstTime.tsx

Added friendly messages

---

src/components/Atoms/WarningAlert.tsx
src/components/Settings/ChangeSelfPasswordForm.tsx
src/components/Settings/ChangeUserPasswordForm.tsx
src/components/Settings/CreateUserForm.tsx
src/components/UserBox.tsx
src/pages/login/CoreConnect.tsx
src/pages/login/CoreSelectExisting.tsx
src/pages/login/CoreSetupNew.tsx
src/pages/login/UserLogin.tsx

Added overall form errors using setStatus from Formik, and used the Warning Banner that was made in another pr so it should merge fine

Added overall form errors

---

src/components/DashboardCard.tsx
src/components/DashboardLayout/InstanceViewLayout.tsx
src/components/DashboardLayout/Spinner.tsx
src/pages/InstanceTabs/InstanceTabs.tsx
src/pages/home.tsx

bro how tf did we leave that page there for so long 💀
---
(tauri)
(fullscreen)

hotfix for home until full design

---

src/components/Atoms/Form/ComboField.tsx
src/components/Instance/Create/FormCreation.tsx
src/components/Instance/Create/SetupFormFields/FormComboField.tsx
src/components/Instance/Create/SetupFormFields/FormInputField.tsx
src/components/Instance/Create/SetupFormFields/FormRadioField.tsx
src/components/Instance/Create/form.ts
src/components/Instance/InstanceCreateForm.tsx
src/globals.css

- Created new field components specifically for the setup page, styling like the settings page but standard form validation with yup
- Modified the default red error colour to red-200
- Added asterisk for required fields, but excluded it for toggles because it will always have a value (default at false).

Setup form styling [Merge this first]

---

src/data/GameTypeMappings.tsx

Fix descriptions for Fabric and Paper

---

src/components/FileViewer/FileViewer.tsx
src/utils/util.ts

unzip into the current directory

---

src/components/FileViewer/FileContextMenu.tsx
src/components/FileViewer/FileList.tsx
src/components/FileViewer/FileViewer.tsx

small changes adding support pasting from the context menu and making files semi transparent when cut

add paste on context menu, add transparency on cut

---

src/components/FileViewer/FileViewer.tsx
src/utils/apis.ts

these changes allow you to download the folder as a zip. must be run with the changes made to the backend to work

make changes to support downloading folder

---

dashboard/src/components/DashboardLayout/DashboardLayout.tsx

Removed timeout from core connection error detect and changed labels on popup.

removed timeout on connection error and popup

---

core/src/lib.rs

Added check with map for when duplicate UUIDs are detected (e.g. if a user copy-pastes an instance config file)

feat: added logging for duplicate uuids

---

.github/workflows/dashboard-release-docker.yml
dashboard/.dockerignore
dashboard/Dockerfile
dashboard/public/mockServiceWorker.js

Add docker image for dashboard

---

.github/workflows/core-release-docker.yml
.github/workflows/dashboard-release-docker.yml

Update package names for docker files to be consistent:
core: ghci.io/lodestone-team/lodestone_core
dashboard: ghci.io/lodestone-team/lodestone_dashboard

Consistent naming for docker packages

---

.github/workflows/dashboard-build-and-draft.yml

Remove mac build
